// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutIntro: typeof import('./src/components/about/AboutIntro.vue')['default']
    AboutStory: typeof import('./src/components/about/AboutStory.vue')['default']
    ArticleItem: typeof import('./src/components/articles/ArticleItem.vue')['default']
    ArticleList: typeof import('./src/components/articles/ArticleList.vue')['default']
    ContactForm: typeof import('./src/components/contacts/ContactForm.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HomeClientProjects: typeof import('./src/components/home/HomeClientProjects.vue')['default']
    HomeHero: typeof import('./src/components/home/HomeHero.vue')['default']
    HomePersonalProjects: typeof import('./src/components/home/HomePersonalProjects.vue')['default']
    NextIcon: typeof import('./src/components/project/NextIcon.vue')['default']
    PCallToAction: typeof import('./src/components/shared/PCallToAction.vue')['default']
    PLinkButton: typeof import('./src/components/shared/PLinkButton.vue')['default']
    PProjectCard: typeof import('./src/components/shared/PProjectCard.vue')['default']
    PrevIcon: typeof import('./src/components/project/PrevIcon.vue')['default']
    ProjectCard: typeof import('./src/components/skeletons/ProjectCard.vue')['default']
    ProjectCardSceleton: typeof import('./src/components/skeletons/ProjectCardSceleton.vue')['default']
    ProjectCardSkeleton: typeof import('./src/components/skeletons/ProjectCardSkeleton.vue')['default']
    ProjectDetails: typeof import('./src/components/project/ProjectDetails.vue')['default']
    ProjectDetailsCategories: typeof import('./src/components/project/ProjectDetailsCategories.vue')['default']
    ProjectDetailsSkeleton: typeof import('./src/components/skeletons/ProjectDetailsSkeleton.vue')['default']
    PSignitureText: typeof import('./src/components/shared/PSignitureText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stats: typeof import('./src/components/about/Stats.vue')['default']
  }
}
