// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./src/components/articles/ArticleItem.vue')['default']
    ArticleList: typeof import('./src/components/articles/ArticleList.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeroHome: typeof import('./src/components/home/HeroHome.vue')['default']
    HomeClientProjects: typeof import('./src/components/home/HomeClientProjects.vue')['default']
    HomeHeader: typeof import('./src/components/home/HomeHeader.vue')['default']
    HomeHero: typeof import('./src/components/home/HomeHero.vue')['default']
    HomePersonalProjects: typeof import('./src/components/home/HomePersonalProjects.vue')['default']
    PCallToAction: typeof import('./src/components/shared/PCallToAction.vue')['default']
    PLinkButton: typeof import('./src/components/shared/PLinkButton.vue')['default']
    PProjectCard: typeof import('./src/components/shared/PProjectCard.vue')['default']
    PSignitureText: typeof import('./src/components/shared/PSignitureText.vue')['default']
    PTitleDescription: typeof import('./src/components/shared/PTitleDescription.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
